version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: openinfra_gis
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/openinfra_gis?authSource=openinfra_gis
      - VIETMAP_API_KEY=${VIETMAP_API_KEY:-c3fb93ce07177490296477158d6475046fe634dd8ffd494c}
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5175:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
