/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicianRouteImport } from './routes/technician'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnicianIndexRouteImport } from './routes/technician/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicReportRouteImport } from './routes/public/report'
import { Route as AssetIdRouteImport } from './routes/asset.$id'
import { Route as AdminMapRouteImport } from './routes/admin/map'
import { Route as AdminIngestRouteImport } from './routes/admin/ingest'
import { Route as TechnicianSettingsIndexRouteImport } from './routes/technician/settings/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminIotIndexRouteImport } from './routes/admin/iot/index'
import { Route as AdminIncidentsIndexRouteImport } from './routes/admin/incidents/index'
import { Route as AdminBudgetsIndexRouteImport } from './routes/admin/budgets/index'
import { Route as AdminAssetsIndexRouteImport } from './routes/admin/assets/index'
import { Route as AdminAlertsIndexRouteImport } from './routes/admin/alerts/index'
import { Route as TechnicianTasksTaskIdRouteImport } from './routes/technician/tasks.$taskId'
import { Route as TechnicianMaintenanceIdRouteImport } from './routes/technician/maintenance.$id'
import { Route as PublicReportAssetIdRouteImport } from './routes/public/report.$assetId'
import { Route as PublicIncidentsIncidentIdRouteImport } from './routes/public/incidents.$incidentId'
import { Route as AdminUsersCreateRouteImport } from './routes/admin/users/create'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users/$id'
import { Route as AdminReportsCreateRouteImport } from './routes/admin/reports/create'
import { Route as AdminIotCreateRouteImport } from './routes/admin/iot/create'
import { Route as AdminIotIdRouteImport } from './routes/admin/iot/$id'
import { Route as AdminIncidentsCreateRouteImport } from './routes/admin/incidents/create'
import { Route as AdminIncidentsIdRouteImport } from './routes/admin/incidents/$id'
import { Route as AdminBudgetsCreateRouteImport } from './routes/admin/budgets/create'
import { Route as AdminBudgetsIdRouteImport } from './routes/admin/budgets/$id'
import { Route as AdminAssetsIdRouteImport } from './routes/admin/assets/$id'
import { Route as AdminAlertsListRouteImport } from './routes/admin/alerts/list'

const TechnicianRoute = TechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianIndexRoute = TechnicianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechnicianRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicReportRoute = PublicReportRouteImport.update({
  id: '/public/report',
  path: '/public/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIdRoute = AssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIngestRoute = AdminIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => AdminRoute,
} as any)
const TechnicianSettingsIndexRoute = TechnicianSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => TechnicianRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIotIndexRoute = AdminIotIndexRouteImport.update({
  id: '/iot/',
  path: '/iot/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncidentsIndexRoute = AdminIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBudgetsIndexRoute = AdminBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsIndexRoute = AdminAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsIndexRoute = AdminAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AdminRoute,
} as any)
const TechnicianTasksTaskIdRoute = TechnicianTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => TechnicianRoute,
} as any)
const TechnicianMaintenanceIdRoute = TechnicianMaintenanceIdRouteImport.update({
  id: '/maintenance/$id',
  path: '/maintenance/$id',
  getParentRoute: () => TechnicianRoute,
} as any)
const PublicReportAssetIdRoute = PublicReportAssetIdRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => PublicReportRoute,
} as any)
const PublicIncidentsIncidentIdRoute =
  PublicIncidentsIncidentIdRouteImport.update({
    id: '/public/incidents/$incidentId',
    path: '/public/incidents/$incidentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersCreateRoute = AdminUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsCreateRoute = AdminReportsCreateRouteImport.update({
  id: '/reports/create',
  path: '/reports/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIotCreateRoute = AdminIotCreateRouteImport.update({
  id: '/iot/create',
  path: '/iot/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIotIdRoute = AdminIotIdRouteImport.update({
  id: '/iot/$id',
  path: '/iot/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncidentsCreateRoute = AdminIncidentsCreateRouteImport.update({
  id: '/incidents/create',
  path: '/incidents/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncidentsIdRoute = AdminIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBudgetsCreateRoute = AdminBudgetsCreateRouteImport.update({
  id: '/budgets/create',
  path: '/budgets/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBudgetsIdRoute = AdminBudgetsIdRouteImport.update({
  id: '/budgets/$id',
  path: '/budgets/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsIdRoute = AdminAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsListRoute = AdminAlertsListRouteImport.update({
  id: '/alerts/list',
  path: '/alerts/list',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/register': typeof RegisterRoute
  '/technician': typeof TechnicianRouteWithChildren
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/map': typeof AdminMapRoute
  '/asset/$id': typeof AssetIdRoute
  '/public/report': typeof PublicReportRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/admin/alerts/list': typeof AdminAlertsListRoute
  '/admin/assets/$id': typeof AdminAssetsIdRoute
  '/admin/budgets/$id': typeof AdminBudgetsIdRoute
  '/admin/budgets/create': typeof AdminBudgetsCreateRoute
  '/admin/incidents/$id': typeof AdminIncidentsIdRoute
  '/admin/incidents/create': typeof AdminIncidentsCreateRoute
  '/admin/iot/$id': typeof AdminIotIdRoute
  '/admin/iot/create': typeof AdminIotCreateRoute
  '/admin/reports/create': typeof AdminReportsCreateRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/public/incidents/$incidentId': typeof PublicIncidentsIncidentIdRoute
  '/public/report/$assetId': typeof PublicReportAssetIdRoute
  '/technician/maintenance/$id': typeof TechnicianMaintenanceIdRoute
  '/technician/tasks/$taskId': typeof TechnicianTasksTaskIdRoute
  '/admin/alerts': typeof AdminAlertsIndexRoute
  '/admin/assets': typeof AdminAssetsIndexRoute
  '/admin/budgets': typeof AdminBudgetsIndexRoute
  '/admin/incidents': typeof AdminIncidentsIndexRoute
  '/admin/iot': typeof AdminIotIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/technician/settings': typeof TechnicianSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/register': typeof RegisterRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/map': typeof AdminMapRoute
  '/asset/$id': typeof AssetIdRoute
  '/public/report': typeof PublicReportRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/technician': typeof TechnicianIndexRoute
  '/admin/alerts/list': typeof AdminAlertsListRoute
  '/admin/assets/$id': typeof AdminAssetsIdRoute
  '/admin/budgets/$id': typeof AdminBudgetsIdRoute
  '/admin/budgets/create': typeof AdminBudgetsCreateRoute
  '/admin/incidents/$id': typeof AdminIncidentsIdRoute
  '/admin/incidents/create': typeof AdminIncidentsCreateRoute
  '/admin/iot/$id': typeof AdminIotIdRoute
  '/admin/iot/create': typeof AdminIotCreateRoute
  '/admin/reports/create': typeof AdminReportsCreateRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/public/incidents/$incidentId': typeof PublicIncidentsIncidentIdRoute
  '/public/report/$assetId': typeof PublicReportAssetIdRoute
  '/technician/maintenance/$id': typeof TechnicianMaintenanceIdRoute
  '/technician/tasks/$taskId': typeof TechnicianTasksTaskIdRoute
  '/admin/alerts': typeof AdminAlertsIndexRoute
  '/admin/assets': typeof AdminAssetsIndexRoute
  '/admin/budgets': typeof AdminBudgetsIndexRoute
  '/admin/incidents': typeof AdminIncidentsIndexRoute
  '/admin/iot': typeof AdminIotIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/technician/settings': typeof TechnicianSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/register': typeof RegisterRoute
  '/technician': typeof TechnicianRouteWithChildren
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/map': typeof AdminMapRoute
  '/asset/$id': typeof AssetIdRoute
  '/public/report': typeof PublicReportRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/admin/alerts/list': typeof AdminAlertsListRoute
  '/admin/assets/$id': typeof AdminAssetsIdRoute
  '/admin/budgets/$id': typeof AdminBudgetsIdRoute
  '/admin/budgets/create': typeof AdminBudgetsCreateRoute
  '/admin/incidents/$id': typeof AdminIncidentsIdRoute
  '/admin/incidents/create': typeof AdminIncidentsCreateRoute
  '/admin/iot/$id': typeof AdminIotIdRoute
  '/admin/iot/create': typeof AdminIotCreateRoute
  '/admin/reports/create': typeof AdminReportsCreateRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/public/incidents/$incidentId': typeof PublicIncidentsIncidentIdRoute
  '/public/report/$assetId': typeof PublicReportAssetIdRoute
  '/technician/maintenance/$id': typeof TechnicianMaintenanceIdRoute
  '/technician/tasks/$taskId': typeof TechnicianTasksTaskIdRoute
  '/admin/alerts/': typeof AdminAlertsIndexRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
  '/admin/budgets/': typeof AdminBudgetsIndexRoute
  '/admin/incidents/': typeof AdminIncidentsIndexRoute
  '/admin/iot/': typeof AdminIotIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/technician/settings/': typeof TechnicianSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/docs'
    | '/login'
    | '/map'
    | '/register'
    | '/technician'
    | '/admin/ingest'
    | '/admin/map'
    | '/asset/$id'
    | '/public/report'
    | '/admin/'
    | '/technician/'
    | '/admin/alerts/list'
    | '/admin/assets/$id'
    | '/admin/budgets/$id'
    | '/admin/budgets/create'
    | '/admin/incidents/$id'
    | '/admin/incidents/create'
    | '/admin/iot/$id'
    | '/admin/iot/create'
    | '/admin/reports/create'
    | '/admin/users/$id'
    | '/admin/users/create'
    | '/public/incidents/$incidentId'
    | '/public/report/$assetId'
    | '/technician/maintenance/$id'
    | '/technician/tasks/$taskId'
    | '/admin/alerts'
    | '/admin/assets'
    | '/admin/budgets'
    | '/admin/incidents'
    | '/admin/iot'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/technician/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs'
    | '/login'
    | '/map'
    | '/register'
    | '/admin/ingest'
    | '/admin/map'
    | '/asset/$id'
    | '/public/report'
    | '/admin'
    | '/technician'
    | '/admin/alerts/list'
    | '/admin/assets/$id'
    | '/admin/budgets/$id'
    | '/admin/budgets/create'
    | '/admin/incidents/$id'
    | '/admin/incidents/create'
    | '/admin/iot/$id'
    | '/admin/iot/create'
    | '/admin/reports/create'
    | '/admin/users/$id'
    | '/admin/users/create'
    | '/public/incidents/$incidentId'
    | '/public/report/$assetId'
    | '/technician/maintenance/$id'
    | '/technician/tasks/$taskId'
    | '/admin/alerts'
    | '/admin/assets'
    | '/admin/budgets'
    | '/admin/incidents'
    | '/admin/iot'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/technician/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/docs'
    | '/login'
    | '/map'
    | '/register'
    | '/technician'
    | '/admin/ingest'
    | '/admin/map'
    | '/asset/$id'
    | '/public/report'
    | '/admin/'
    | '/technician/'
    | '/admin/alerts/list'
    | '/admin/assets/$id'
    | '/admin/budgets/$id'
    | '/admin/budgets/create'
    | '/admin/incidents/$id'
    | '/admin/incidents/create'
    | '/admin/iot/$id'
    | '/admin/iot/create'
    | '/admin/reports/create'
    | '/admin/users/$id'
    | '/admin/users/create'
    | '/public/incidents/$incidentId'
    | '/public/report/$assetId'
    | '/technician/maintenance/$id'
    | '/technician/tasks/$taskId'
    | '/admin/alerts/'
    | '/admin/assets/'
    | '/admin/budgets/'
    | '/admin/incidents/'
    | '/admin/iot/'
    | '/admin/reports/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/technician/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  RegisterRoute: typeof RegisterRoute
  TechnicianRoute: typeof TechnicianRouteWithChildren
  AssetIdRoute: typeof AssetIdRoute
  PublicReportRoute: typeof PublicReportRouteWithChildren
  PublicIncidentsIncidentIdRoute: typeof PublicIncidentsIncidentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technician': {
      id: '/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof TechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/': {
      id: '/technician/'
      path: '/'
      fullPath: '/technician/'
      preLoaderRoute: typeof TechnicianIndexRouteImport
      parentRoute: typeof TechnicianRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/public/report': {
      id: '/public/report'
      path: '/public/report'
      fullPath: '/public/report'
      preLoaderRoute: typeof PublicReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$id': {
      id: '/asset/$id'
      path: '/asset/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ingest': {
      id: '/admin/ingest'
      path: '/ingest'
      fullPath: '/admin/ingest'
      preLoaderRoute: typeof AdminIngestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/technician/settings/': {
      id: '/technician/settings/'
      path: '/settings'
      fullPath: '/technician/settings'
      preLoaderRoute: typeof TechnicianSettingsIndexRouteImport
      parentRoute: typeof TechnicianRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iot/': {
      id: '/admin/iot/'
      path: '/iot'
      fullPath: '/admin/iot'
      preLoaderRoute: typeof AdminIotIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incidents/': {
      id: '/admin/incidents/'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AdminIncidentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/budgets/': {
      id: '/admin/budgets/'
      path: '/budgets'
      fullPath: '/admin/budgets'
      preLoaderRoute: typeof AdminBudgetsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/': {
      id: '/admin/assets/'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts/': {
      id: '/admin/alerts/'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/technician/tasks/$taskId': {
      id: '/technician/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/technician/tasks/$taskId'
      preLoaderRoute: typeof TechnicianTasksTaskIdRouteImport
      parentRoute: typeof TechnicianRoute
    }
    '/technician/maintenance/$id': {
      id: '/technician/maintenance/$id'
      path: '/maintenance/$id'
      fullPath: '/technician/maintenance/$id'
      preLoaderRoute: typeof TechnicianMaintenanceIdRouteImport
      parentRoute: typeof TechnicianRoute
    }
    '/public/report/$assetId': {
      id: '/public/report/$assetId'
      path: '/$assetId'
      fullPath: '/public/report/$assetId'
      preLoaderRoute: typeof PublicReportAssetIdRouteImport
      parentRoute: typeof PublicReportRoute
    }
    '/public/incidents/$incidentId': {
      id: '/public/incidents/$incidentId'
      path: '/public/incidents/$incidentId'
      fullPath: '/public/incidents/$incidentId'
      preLoaderRoute: typeof PublicIncidentsIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/create': {
      id: '/admin/users/create'
      path: '/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AdminUsersCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/create': {
      id: '/admin/reports/create'
      path: '/reports/create'
      fullPath: '/admin/reports/create'
      preLoaderRoute: typeof AdminReportsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iot/create': {
      id: '/admin/iot/create'
      path: '/iot/create'
      fullPath: '/admin/iot/create'
      preLoaderRoute: typeof AdminIotCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iot/$id': {
      id: '/admin/iot/$id'
      path: '/iot/$id'
      fullPath: '/admin/iot/$id'
      preLoaderRoute: typeof AdminIotIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incidents/create': {
      id: '/admin/incidents/create'
      path: '/incidents/create'
      fullPath: '/admin/incidents/create'
      preLoaderRoute: typeof AdminIncidentsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incidents/$id': {
      id: '/admin/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/admin/incidents/$id'
      preLoaderRoute: typeof AdminIncidentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/budgets/create': {
      id: '/admin/budgets/create'
      path: '/budgets/create'
      fullPath: '/admin/budgets/create'
      preLoaderRoute: typeof AdminBudgetsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/budgets/$id': {
      id: '/admin/budgets/$id'
      path: '/budgets/$id'
      fullPath: '/admin/budgets/$id'
      preLoaderRoute: typeof AdminBudgetsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/$id': {
      id: '/admin/assets/$id'
      path: '/assets/$id'
      fullPath: '/admin/assets/$id'
      preLoaderRoute: typeof AdminAssetsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts/list': {
      id: '/admin/alerts/list'
      path: '/alerts/list'
      fullPath: '/admin/alerts/list'
      preLoaderRoute: typeof AdminAlertsListRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIngestRoute: typeof AdminIngestRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlertsListRoute: typeof AdminAlertsListRoute
  AdminAssetsIdRoute: typeof AdminAssetsIdRoute
  AdminBudgetsIdRoute: typeof AdminBudgetsIdRoute
  AdminBudgetsCreateRoute: typeof AdminBudgetsCreateRoute
  AdminIncidentsIdRoute: typeof AdminIncidentsIdRoute
  AdminIncidentsCreateRoute: typeof AdminIncidentsCreateRoute
  AdminIotIdRoute: typeof AdminIotIdRoute
  AdminIotCreateRoute: typeof AdminIotCreateRoute
  AdminReportsCreateRoute: typeof AdminReportsCreateRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersCreateRoute: typeof AdminUsersCreateRoute
  AdminAlertsIndexRoute: typeof AdminAlertsIndexRoute
  AdminAssetsIndexRoute: typeof AdminAssetsIndexRoute
  AdminBudgetsIndexRoute: typeof AdminBudgetsIndexRoute
  AdminIncidentsIndexRoute: typeof AdminIncidentsIndexRoute
  AdminIotIndexRoute: typeof AdminIotIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIngestRoute: AdminIngestRoute,
  AdminMapRoute: AdminMapRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAlertsListRoute: AdminAlertsListRoute,
  AdminAssetsIdRoute: AdminAssetsIdRoute,
  AdminBudgetsIdRoute: AdminBudgetsIdRoute,
  AdminBudgetsCreateRoute: AdminBudgetsCreateRoute,
  AdminIncidentsIdRoute: AdminIncidentsIdRoute,
  AdminIncidentsCreateRoute: AdminIncidentsCreateRoute,
  AdminIotIdRoute: AdminIotIdRoute,
  AdminIotCreateRoute: AdminIotCreateRoute,
  AdminReportsCreateRoute: AdminReportsCreateRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersCreateRoute: AdminUsersCreateRoute,
  AdminAlertsIndexRoute: AdminAlertsIndexRoute,
  AdminAssetsIndexRoute: AdminAssetsIndexRoute,
  AdminBudgetsIndexRoute: AdminBudgetsIndexRoute,
  AdminIncidentsIndexRoute: AdminIncidentsIndexRoute,
  AdminIotIndexRoute: AdminIotIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TechnicianRouteChildren {
  TechnicianIndexRoute: typeof TechnicianIndexRoute
  TechnicianMaintenanceIdRoute: typeof TechnicianMaintenanceIdRoute
  TechnicianTasksTaskIdRoute: typeof TechnicianTasksTaskIdRoute
  TechnicianSettingsIndexRoute: typeof TechnicianSettingsIndexRoute
}

const TechnicianRouteChildren: TechnicianRouteChildren = {
  TechnicianIndexRoute: TechnicianIndexRoute,
  TechnicianMaintenanceIdRoute: TechnicianMaintenanceIdRoute,
  TechnicianTasksTaskIdRoute: TechnicianTasksTaskIdRoute,
  TechnicianSettingsIndexRoute: TechnicianSettingsIndexRoute,
}

const TechnicianRouteWithChildren = TechnicianRoute._addFileChildren(
  TechnicianRouteChildren,
)

interface PublicReportRouteChildren {
  PublicReportAssetIdRoute: typeof PublicReportAssetIdRoute
}

const PublicReportRouteChildren: PublicReportRouteChildren = {
  PublicReportAssetIdRoute: PublicReportAssetIdRoute,
}

const PublicReportRouteWithChildren = PublicReportRoute._addFileChildren(
  PublicReportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  RegisterRoute: RegisterRoute,
  TechnicianRoute: TechnicianRouteWithChildren,
  AssetIdRoute: AssetIdRoute,
  PublicReportRoute: PublicReportRouteWithChildren,
  PublicIncidentsIncidentIdRoute: PublicIncidentsIncidentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
