/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicReportRouteImport } from './routes/public/report'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminIotIndexRouteImport } from './routes/admin/iot/index'
import { Route as AdminIncidentsIndexRouteImport } from './routes/admin/incidents/index'
import { Route as AdminBudgetsIndexRouteImport } from './routes/admin/budgets/index'
import { Route as AdminAlertsIndexRouteImport } from './routes/admin/alerts/index'
import { Route as AdminUsersCreateRouteImport } from './routes/admin/users/create'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users/$id'
import { Route as AdminReportsCreateRouteImport } from './routes/admin/reports/create'
import { Route as AdminIotCreateRouteImport } from './routes/admin/iot/create'
import { Route as AdminIotIdRouteImport } from './routes/admin/iot/$id'
import { Route as AdminIncidentsCreateRouteImport } from './routes/admin/incidents/create'
import { Route as AdminIncidentsIdRouteImport } from './routes/admin/incidents/$id'
import { Route as AdminBudgetsCreateRouteImport } from './routes/admin/budgets/create'
import { Route as AdminBudgetsIdRouteImport } from './routes/admin/budgets/$id'
import { Route as AdminAlertsListRouteImport } from './routes/admin/alerts/list'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicReportRoute = PublicReportRouteImport.update({
  id: '/public/report',
  path: '/public/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIotIndexRoute = AdminIotIndexRouteImport.update({
  id: '/iot/',
  path: '/iot/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncidentsIndexRoute = AdminIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBudgetsIndexRoute = AdminBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsIndexRoute = AdminAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersCreateRoute = AdminUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsCreateRoute = AdminReportsCreateRouteImport.update({
  id: '/reports/create',
  path: '/reports/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIotCreateRoute = AdminIotCreateRouteImport.update({
  id: '/iot/create',
  path: '/iot/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIotIdRoute = AdminIotIdRouteImport.update({
  id: '/iot/$id',
  path: '/iot/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncidentsCreateRoute = AdminIncidentsCreateRouteImport.update({
  id: '/incidents/create',
  path: '/incidents/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncidentsIdRoute = AdminIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBudgetsCreateRoute = AdminBudgetsCreateRouteImport.update({
  id: '/budgets/create',
  path: '/budgets/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBudgetsIdRoute = AdminBudgetsIdRouteImport.update({
  id: '/budgets/$id',
  path: '/budgets/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsListRoute = AdminAlertsListRouteImport.update({
  id: '/alerts/list',
  path: '/alerts/list',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/register': typeof RegisterRoute
  '/public/report': typeof PublicReportRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alerts/list': typeof AdminAlertsListRoute
  '/admin/budgets/$id': typeof AdminBudgetsIdRoute
  '/admin/budgets/create': typeof AdminBudgetsCreateRoute
  '/admin/incidents/$id': typeof AdminIncidentsIdRoute
  '/admin/incidents/create': typeof AdminIncidentsCreateRoute
  '/admin/iot/$id': typeof AdminIotIdRoute
  '/admin/iot/create': typeof AdminIotCreateRoute
  '/admin/reports/create': typeof AdminReportsCreateRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/admin/alerts': typeof AdminAlertsIndexRoute
  '/admin/budgets': typeof AdminBudgetsIndexRoute
  '/admin/incidents': typeof AdminIncidentsIndexRoute
  '/admin/iot': typeof AdminIotIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/register': typeof RegisterRoute
  '/public/report': typeof PublicReportRoute
  '/admin': typeof AdminIndexRoute
  '/admin/alerts/list': typeof AdminAlertsListRoute
  '/admin/budgets/$id': typeof AdminBudgetsIdRoute
  '/admin/budgets/create': typeof AdminBudgetsCreateRoute
  '/admin/incidents/$id': typeof AdminIncidentsIdRoute
  '/admin/incidents/create': typeof AdminIncidentsCreateRoute
  '/admin/iot/$id': typeof AdminIotIdRoute
  '/admin/iot/create': typeof AdminIotCreateRoute
  '/admin/reports/create': typeof AdminReportsCreateRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/admin/alerts': typeof AdminAlertsIndexRoute
  '/admin/budgets': typeof AdminBudgetsIndexRoute
  '/admin/incidents': typeof AdminIncidentsIndexRoute
  '/admin/iot': typeof AdminIotIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/register': typeof RegisterRoute
  '/public/report': typeof PublicReportRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alerts/list': typeof AdminAlertsListRoute
  '/admin/budgets/$id': typeof AdminBudgetsIdRoute
  '/admin/budgets/create': typeof AdminBudgetsCreateRoute
  '/admin/incidents/$id': typeof AdminIncidentsIdRoute
  '/admin/incidents/create': typeof AdminIncidentsCreateRoute
  '/admin/iot/$id': typeof AdminIotIdRoute
  '/admin/iot/create': typeof AdminIotCreateRoute
  '/admin/reports/create': typeof AdminReportsCreateRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/admin/alerts/': typeof AdminAlertsIndexRoute
  '/admin/budgets/': typeof AdminBudgetsIndexRoute
  '/admin/incidents/': typeof AdminIncidentsIndexRoute
  '/admin/iot/': typeof AdminIotIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/map'
    | '/register'
    | '/public/report'
    | '/admin/'
    | '/admin/alerts/list'
    | '/admin/budgets/$id'
    | '/admin/budgets/create'
    | '/admin/incidents/$id'
    | '/admin/incidents/create'
    | '/admin/iot/$id'
    | '/admin/iot/create'
    | '/admin/reports/create'
    | '/admin/users/$id'
    | '/admin/users/create'
    | '/admin/alerts'
    | '/admin/budgets'
    | '/admin/incidents'
    | '/admin/iot'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/map'
    | '/register'
    | '/public/report'
    | '/admin'
    | '/admin/alerts/list'
    | '/admin/budgets/$id'
    | '/admin/budgets/create'
    | '/admin/incidents/$id'
    | '/admin/incidents/create'
    | '/admin/iot/$id'
    | '/admin/iot/create'
    | '/admin/reports/create'
    | '/admin/users/$id'
    | '/admin/users/create'
    | '/admin/alerts'
    | '/admin/budgets'
    | '/admin/incidents'
    | '/admin/iot'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/map'
    | '/register'
    | '/public/report'
    | '/admin/'
    | '/admin/alerts/list'
    | '/admin/budgets/$id'
    | '/admin/budgets/create'
    | '/admin/incidents/$id'
    | '/admin/incidents/create'
    | '/admin/iot/$id'
    | '/admin/iot/create'
    | '/admin/reports/create'
    | '/admin/users/$id'
    | '/admin/users/create'
    | '/admin/alerts/'
    | '/admin/budgets/'
    | '/admin/incidents/'
    | '/admin/iot/'
    | '/admin/reports/'
    | '/admin/settings/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  RegisterRoute: typeof RegisterRoute
  PublicReportRoute: typeof PublicReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/public/report': {
      id: '/public/report'
      path: '/public/report'
      fullPath: '/public/report'
      preLoaderRoute: typeof PublicReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iot/': {
      id: '/admin/iot/'
      path: '/iot'
      fullPath: '/admin/iot'
      preLoaderRoute: typeof AdminIotIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incidents/': {
      id: '/admin/incidents/'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AdminIncidentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/budgets/': {
      id: '/admin/budgets/'
      path: '/budgets'
      fullPath: '/admin/budgets'
      preLoaderRoute: typeof AdminBudgetsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts/': {
      id: '/admin/alerts/'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/create': {
      id: '/admin/users/create'
      path: '/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AdminUsersCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/create': {
      id: '/admin/reports/create'
      path: '/reports/create'
      fullPath: '/admin/reports/create'
      preLoaderRoute: typeof AdminReportsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iot/create': {
      id: '/admin/iot/create'
      path: '/iot/create'
      fullPath: '/admin/iot/create'
      preLoaderRoute: typeof AdminIotCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iot/$id': {
      id: '/admin/iot/$id'
      path: '/iot/$id'
      fullPath: '/admin/iot/$id'
      preLoaderRoute: typeof AdminIotIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incidents/create': {
      id: '/admin/incidents/create'
      path: '/incidents/create'
      fullPath: '/admin/incidents/create'
      preLoaderRoute: typeof AdminIncidentsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incidents/$id': {
      id: '/admin/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/admin/incidents/$id'
      preLoaderRoute: typeof AdminIncidentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/budgets/create': {
      id: '/admin/budgets/create'
      path: '/budgets/create'
      fullPath: '/admin/budgets/create'
      preLoaderRoute: typeof AdminBudgetsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/budgets/$id': {
      id: '/admin/budgets/$id'
      path: '/budgets/$id'
      fullPath: '/admin/budgets/$id'
      preLoaderRoute: typeof AdminBudgetsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts/list': {
      id: '/admin/alerts/list'
      path: '/alerts/list'
      fullPath: '/admin/alerts/list'
      preLoaderRoute: typeof AdminAlertsListRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlertsListRoute: typeof AdminAlertsListRoute
  AdminBudgetsIdRoute: typeof AdminBudgetsIdRoute
  AdminBudgetsCreateRoute: typeof AdminBudgetsCreateRoute
  AdminIncidentsIdRoute: typeof AdminIncidentsIdRoute
  AdminIncidentsCreateRoute: typeof AdminIncidentsCreateRoute
  AdminIotIdRoute: typeof AdminIotIdRoute
  AdminIotCreateRoute: typeof AdminIotCreateRoute
  AdminReportsCreateRoute: typeof AdminReportsCreateRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersCreateRoute: typeof AdminUsersCreateRoute
  AdminAlertsIndexRoute: typeof AdminAlertsIndexRoute
  AdminBudgetsIndexRoute: typeof AdminBudgetsIndexRoute
  AdminIncidentsIndexRoute: typeof AdminIncidentsIndexRoute
  AdminIotIndexRoute: typeof AdminIotIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAlertsListRoute: AdminAlertsListRoute,
  AdminBudgetsIdRoute: AdminBudgetsIdRoute,
  AdminBudgetsCreateRoute: AdminBudgetsCreateRoute,
  AdminIncidentsIdRoute: AdminIncidentsIdRoute,
  AdminIncidentsCreateRoute: AdminIncidentsCreateRoute,
  AdminIotIdRoute: AdminIotIdRoute,
  AdminIotCreateRoute: AdminIotCreateRoute,
  AdminReportsCreateRoute: AdminReportsCreateRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersCreateRoute: AdminUsersCreateRoute,
  AdminAlertsIndexRoute: AdminAlertsIndexRoute,
  AdminBudgetsIndexRoute: AdminBudgetsIndexRoute,
  AdminIncidentsIndexRoute: AdminIncidentsIndexRoute,
  AdminIotIndexRoute: AdminIotIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  RegisterRoute: RegisterRoute,
  PublicReportRoute: PublicReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
